"""edit favorite locations

Revision ID: 685a8f138528
Revises: cdd254828f52
Create Date: 2026-08-23 12:29:53.125757

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "685a8f138528"
down_revision: str | Sequence[str] | None = "cdd254828f52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_favorite_locations_location_id"), table_name="favorite_locations"
    )
    op.drop_index(
        op.f("ix_favorite_locations_profile_id"), table_name="favorite_locations"
    )
    op.drop_column("favorite_locations", "updated_at")
    op.drop_column("favorite_locations", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "favorite_locations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "favorite_locations",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_favorite_locations_profile_id"),
        "favorite_locations",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_locations_location_id"),
        "favorite_locations",
        ["location_id"],
        unique=False,
    )
    # ### end Alembic commands ###
