"""replace city and country with ids

Revision ID: 6881ffc708ea
Revises: 9d648fb8d1b9
Create Date: 2026-09-23 17:52:22.279582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6881ffc708ea'
down_revision: Union[str, Sequence[str], None] = '9d648fb8d1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('city_id', sa.Integer(), nullable=True))
    op.drop_column('profiles', 'country')
    op.drop_column('profiles', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'city_id')
    op.drop_column('profiles', 'country_id')
    # ### end Alembic commands ###
