"""add profile settings

Revision ID: 9d648fb8d1b9
Revises: f9c842478df7
Create Date: 2026-09-16 13:14:03.035550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d648fb8d1b9'
down_revision: Union[str, Sequence[str], None] = 'f9c842478df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NOW_DEFAULT = sa.text('now()')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_settings',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('show_profile', sa.Boolean(), nullable=False),
    sa.Column('show_name_in_reviews', sa.Boolean(), nullable=False),
    sa.Column('use_activity_for_recommendations', sa.Boolean(), nullable=False),
    sa.Column('use_profile_for_recommendations', sa.Boolean(), nullable=False),
    sa.Column('use_city_for_tour_matching', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=NOW_DEFAULT, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=NOW_DEFAULT, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.alter_column('profile_devices', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=NOW_DEFAULT)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_devices', 'last_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=NOW_DEFAULT)
    op.drop_table('profile_settings')
    # ### end Alembic commands ###
