"""add favorite_location_ids to profiles

Revision ID: bd475b587033
Revises: f2e4b8a3c901
Create Date: 2026-08-19 13:53:26.058533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd475b587033'
down_revision: Union[str, Sequence[str], None] = 'f2e4b8a3c901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('favorite_location_ids', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'favorite_location_ids')
    # ### end Alembic commands ###
