"""add favorite locations

Revision ID: cdd254828f52
Revises: f2e4b8a3c901
Create Date: 2026-08-20 14:10:08.398067

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdd254828f52"
down_revision: str | Sequence[str] | None = "f2e4b8a3c901"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "location_id", name="uq_favorite_locations_profile_location"
        ),
    )
    op.create_index(
        op.f("ix_favorite_locations_location_id"),
        "favorite_locations",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_locations_profile_id"),
        "favorite_locations",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_favorite_locations_profile_id"), table_name="favorite_locations"
    )
    op.drop_index(
        op.f("ix_favorite_locations_location_id"), table_name="favorite_locations"
    )
    op.drop_table("favorite_locations")
    # ### end Alembic commands ###
